version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - external
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:80"
      - "5001:443"

networks:
  external:
    driver: bridge